### ISSUE TITLE
New version crashes on startup

### ISSUE THREAD

**Issue by VGmaster670** [RiiConnect24/RiiTag-RPC#12]
The new Windows version of Riitag-RPC crashes about 5-10 sec after launching and closes itself really fast but I was able to get a screenshot of the error. I'm also launching it normally and not running it as administrator.
https://user-images.githubusercontent.com/72361126/97905750-869c3b00-1d10-11eb-8933-bd2dd498b520.png (Let me know if screenshot link doesn't work)

**Comment by DismissedGuy** [comment]
pyinstaller has had issues with sentry_sdk in the past, because it can't detect the hidden imports. Trying to add this file with some modifications as a build hook right now, we'll see if that fixes it: https://github.com/DismissedGuy/wiimmfi-rpc/blob/master/buildhooks/hook-sentry_sdk.py

**Comment by DismissedGuy** [comment]
@VGmaster670 can you try this build?

https://github.com/RiiConnect24/RiiTag-RPC/actions/runs/342313442

**Comment by VGmaster670** [comment]
At first said cannot open archive file but after opening it again it works

**Comment by DismissedGuy** [comment]
I just pushed v1.1.4 which has reportedly fixed this issue.
