### ISSUE TITLE
RiiTag-RPC not doing anything on Mac

### ISSUE THREAD

**Issue by CoopPlayzz** [RiiConnect24/RiiTag-RPC#15]
I can't open it as a application and I dont get any response in terminal.  is this a issue or am I doing it wrong?

**Comment by CoopPlayzz** [comment]
update: it works on pc so it might be Mac. related

**Comment by DismissedGuy** [comment]
Hey! It's possible that the program doesn't function properly on Mac, I (and afaik nobody else) has tested it to see if it's working, so support is mostly based on assumptions.

You can try running the program through a terminal window so it doesn't close, that should allow you to see the stacktrace when it crashes.

**Comment by MilGreat2010** [comment]
<img width="682" alt="Schermafbeelding 2022-05-02 om 09 33 01" src="https://user-images.githubusercontent.com/57262078/166200012-516e7cde-3779-4442-b856-13dce640ab59.png">
works fine for me, you need to open it by being in the right folder in terminal and saying:  `./riitag-rpc` (if your file is named that way) if it then doesnt work, try `chmod +x riitag-rpc` (in the right folder and if your file is named that way) and then try the ./riitag-rpc methodm again

**Comment by CoopPlayzz** [comment]
ok i will try sometime later

**Comment by CoopPlayzz** [comment]
> <img alt="Schermafbeelding 2022-05-02 om 09 33 01" width="682" src="https://user-images.githubusercontent.com/57262078/166200012-516e7cde-3779-4442-b856-13dce640ab59.png">
> 
> works fine for me, you need try to opening it by being in the right folder in terminal and saying: `./riitag-rpc` (if your file is named that way) if it then doesnt work, try `chmod +x riitag-rpc` (in the right folder and if your file is named that way) and then try the ./riitag-rpc method again

Thanks SO MUCH the `chmod +x riitag-rpc` is the thing I had to do to make it an terminal file thanks so much! @MilGreat2010 

Thanks
@CoopPlayzz
