### ISSUE TITLE
macOS / Linux support - FEATURE REQUEST

### ISSUE THREAD

**Issue by Penglyn** [RiiConnect24/RiiTag-RPC#17]
I'd love to see RiiTag-rpc supporting macOS and Linux in the near future, as I don't like using Windows, and the tool is currently only available there.

**Comment by KannaKamuiCute** [comment]
yes

**Comment by Penglyn** [comment]
nvm it does support these OS I didn't even realise

**Comment by DismissedGuy** [comment]
Hello! RiiTag-RPC already supports both Linux and macOS - see the latest release: https://github.com/RiiConnect24/RiiTag-RPC/releases/tag/v1.1.4

If these don't work for you, feel free to share the issue you're running into.
