### ISSUE TITLE
Crash when `game_data.last_played` is missing from API response

### ISSUE THREAD

**Issue by SilvazWasTaken** [RiiConnect24/RiiTag-RPC#18]
so i signed in with discord and everything went well until it put me into the menus
![image](https://user-images.githubusercontent.com/112694330/216816645-b17b946b-a109-42be-be79-1a8a8962d339.png)

**Comment by KcrPL** [comment]
RiiTag-RPC currently does not work due to the RiiTag 2.0 update. No one is currently willing and available to update the app and fix it.

**Comment by luissilva1044894** [comment]
@KcrPL What changed? I can do a PR or just fix that error, if you want...

**Comment by DismissedGuy** [comment]
I don't think this is related to the 2.0 update, as the API should be the same as 1.0's. It also works fine for me:

![](https://u.mikealmel.ooo/Cr5slT/direct)

This is probably related the the "last played" bug, where the program isn't receiving information about the last game you played.
@SilvazWasTaken please try using your riitag at least once by firing up a game, then try running the program again. I'm 99% certain that should fix it.

**Comment by DismissedGuy** [comment]
This bug has been fixed in #19 thanks to @luissilva1044894, I published a new release [v1.1.5](https://github.com/RiiConnect24/RiiTag-RPC/releases/tag/v1.1.5) which includes the commit. Updating to the latest release should also fix your issue.
