### ISSUE TITLE
Properly handle Discord client disconnects

### ISSUE THREAD

**Issue by GabubuAvailable** [RiiConnect24/RiiTag-RPC#20]
The software was running on background and when I check, I see that I've got this:
![image](https://user-images.githubusercontent.com/88589756/221415473-337b32c7-6078-4861-b9f3-38532854cd1a.png)

**Comment by DismissedGuy** [comment]
Did you accidentally close Discord or restarted it in any way? The library I'm using cannot distinguish between an invalid configuration and a closed socket...

**Comment by GabubuAvailable** [comment]
@DismissedGuy no I didn't.
