### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by ArenPlaysGames** [RiiConnect24/RiiTag-RPC#21]
Even when running it as an admin, it seemingly loads forever

**Comment by DismissedGuy** [comment]
So first of all, please do not run this program as admin; it wasn't built with administrator privileges in mind and it will only cause more harm than it will fix things.

To troubleshoot this issue, please try the following:
1. Remove any program leftovers, including the executable and the `cache` directory that should have been created
2. Download the latest release from [here](https://github.com/RiiConnect24/RiiTag-RPC/releases)
3. Run the program by double-clicking on the executable, so **without** admin privileges
4. If it gets stuck again, hit the enter key and spacebar a couple times and observe what happens

If these steps don't solve your problem, please post a screenshot of the application as well as the contents of the `config.json` file. That should allow me to see what's going on.

**Comment by DismissedGuy** [comment]
I'm going to close this under the assumption that you fixed your error; feel free to reopen if that's not the case.
