### ISSUE TITLE
Support game names for non-Wii consoles

### ISSUE THREAD

**Issue by DismissedGuy** [RiiConnect24/RiiTag-RPC#22]
Right now RiiTag-RPC only fetches the GameTDB database for Wii titles, which means that it will simply show the game ID whenever it encounters another title. This can be fixed by downloading the database for other consoles as well, and adapting the shown image to be an image of the proper console instead.

**Relevant strings of code:**
https://github.com/RiiConnect24/RiiTag-RPC/blob/5d964281b863f4b26385e9b928ff614604930375/riitag/user.py#L61-L65
https://github.com/RiiConnect24/RiiTag-RPC/blob/5d964281b863f4b26385e9b928ff614604930375/riitag/presence.py#L22

**WiiTDB databases:**
- [Wii](https://www.gametdb.com/wiitdb.txt?LANG=EN)
- [Wii U](https://www.gametdb.com/wiiutdb.txt?LANG=EN)

**Comment by larsenv** [comment]
Only Wii U should be done because 3DS-RPC can do 3DS games without you having to run a program.
