### ISSUE TITLE
Grab cover art from GameTDB

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/RiiTag-RPC#24]
This PR on Dolphin makes it possible to grab any cover on RiiTag. I think RiiTag-RPC should also make it work. https://github.com/dolphin-emu/dolphin/pull/11751

**Comment by DismissedGuy** [comment]
This is interesting. Should/could we just use Dolphin's URL for this or do we want to keep it local? Selfhosting an alternative would also be an option but I don't really see the advantage of that.
