### ISSUE TITLE
[Bug - ArmCord client/arRPC only] Exit button not working

### ISSUE THREAD

**Issue by TheAlienDrew** [RiiConnect24/RiiTag-RPC#30]
OS: Raspberry Pi OS (64-bit)

Trying to use the exit button in the application (assume already logged in) doesn't appear to work, or freezes, not sure what's causing this, but I know for sure it wasn't an issue in **v1.1.4**.

**Comment by TheAlienDrew** [comment]
May or may not be related to the 'freeze' issue in #29

**Comment by DismissedGuy** [comment]
It could indeed be related, but the program also waits for background tasks when you press the exit button before actually exiting. I suppose it's possible that a background thread is hanging for some reason, which would also prevent the program from exiting.

**Comment by DismissedGuy** [comment]
Please try [this](https://github.com/RiiConnect24/RiiTag-RPC/actions/runs/5316140499) release, which sets a timeout for joining the background thread. It might still take a few seconds to exit if that was indeed the issue, but I suppose it's better than doing nothing at all.

**Comment by TheAlienDrew** [comment]
> Please try [this](https://github.com/RiiConnect24/RiiTag-RPC/actions/runs/5316140499) release, which sets a timeout for joining the background thread. It might still take a few seconds to exit if that was indeed the issue, but I suppose it's better than doing nothing at all.

This does fix the exit issue, a little slow (maybe a second), but works now.

**Comment by DismissedGuy** [comment]
Cool, in that case it's most likely pypresence not working well with arRPC. There's not much I can do about that other than the current solution, but a little delay should be acceptable in my opinion.

**Comment by DismissedGuy** [comment]
Should be fixed in https://github.com/OpenAsar/arrpc/pull/39.
