### ISSUE TITLE
How is RiiTag RPC supposed to work on Raspberry Pi, when there's no Discord client for ARM?

### ISSUE THREAD

**Issue by libewa** [RiiConnect24/RiiTag-RPC#31]
When starting `riitag-rpc`, the app hangs a little, and then crashes with this error:
```
+-------------------------------------------------------+
RiiTag-RPC failed to start :/ 

Please contact us with this ID so we can help you out:
0ad92d2b-3b8e-4076-85e4-0ad0dcc36d93
+-------------------------------------------------------+

** Original exception was: **
Error in sys.excepthook:
Traceback (most recent call last):
  File "sentry_sdk/integrations/excepthook.py", line 63, in sentry_sdk_excepthook
  File "start.py", line 54, in on_error
TypeError: print_exception() missing 2 required positional arguments: 'value' and 'tb'

Original exception was:
Traceback (most recent call last):
  File "start.py", line 240, in <module>
  File "start.py", line 235, in main
  File "start.py", line 135, in __init__
  File "riitag/presence.py", line 38, in __init__
  File "pypresence/presence.py", line 13, in __init__
  File "pypresence/baseclient.py", line 28, in __init__
pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
[101854] Failed to execute script 'start' due to unhandled exception!
```
The cause of the error is apparent: Discord is not installed, as it can't run on the Pi's aarch64 architecture.
How is this planned? Am I supposed to use `box64` or Wine (x64)?

**Comment by DismissedGuy** [comment]
Hi,

That's a really good question which I unfortunately do not have an answer to. I added arm64 builds in since it was requested in #27, but if there exists no aarch64 Discord client then I don't know how to run it either. Maybe @TheAlienDrew could shed some light on this.

I am currently still waiting on #29 and #30, but once the rpi binaries are attached to the latest release I'd like to make it more clear that raspberry pi support is based on a best-effort basis. It's simply much too difficult for me to test before every release, and as you can see from those two issues the platform appears to have some weird quirks which do not appear to be present on regular desktops.

**Comment by libewa** [comment]
got the discord client to run (slowly) using box64
steps for ppl googling:
0. be on pi 3 or 4 and install 64 bit pi os
1. get pi-apps: https://github.com/botspot/pi-apps
2. install box64
3. download discord tgz: https://discord.com/api/download?platform=linux&format=tar.gz
4. extract the tgz (to `/usr/local/bin/Discord`): 
```sh
cd ~/Downloads
sudo tar -xzvf -C /usr/local/bin/Discord
```
5. (optional) copy the `Discord.desktop` file to the Desktop (you'll need to edit the `Exec` property:
```sh
cp /usr/local/bin/Discord/Discord.desktop ~/Desktop/Discord.desktop
```
6. run discord:
```sh
box64 /usr/local/bin/Discord/Discord
```
7. profit

**Comment by libewa** [comment]
btw @DismissedGuy can i make an install script for riiconnect rpc on pi-apps?

**Comment by DismissedGuy** [comment]
Sure, although I'd rather not have it in this repo as that would indicate official support. Feel free to put it in your own repo though, I'll put a link to it in the README if you decide to do that.

**Comment by libewa** [comment]
kay, pr opened. thx. (i will sleep now)

**Comment by TheAlienDrew** [comment]
> When starting `riitag-rpc`, the app hangs a little, and then crashes with this error:
> ```
> +-------------------------------------------------------+
> RiiTag-RPC failed to start :/ 
> 
> Please contact us with this ID so we can help you out:
> 0ad92d2b-3b8e-4076-85e4-0ad0dcc36d93
> +-------------------------------------------------------+
> 
> ** Original exception was: **
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "sentry_sdk/integrations/excepthook.py", line 63, in sentry_sdk_excepthook
>   File "start.py", line 54, in on_error
> TypeError: print_exception() missing 2 required positional arguments: 'value' and 'tb'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "start.py", line 240, in <module>
>   File "start.py", line 235, in main
>   File "start.py", line 135, in __init__
>   File "riitag/presence.py", line 38, in __init__
>   File "pypresence/presence.py", line 13, in __init__
>   File "pypresence/baseclient.py", line 28, in __init__
> pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
> [101854] Failed to execute script 'start' due to unhandled exception!
> ```
> The cause of the error is apparent: Discord is not installed, as it can't run on the Pi's aarch64 architecture.
> How is this planned? Am I supposed to use `box64` or Wine (x64)?

I use ArmCord with it, it's a modded electron client of discord that supports arm: https://github.com/ArmCord/ArmCord

And creates its own rich presence server, which is what I use as an automated means of updating my rich presence without having to think about it.

**Comment by TheAlienDrew** [comment]
Also, here's the script I made for getting things working, at least for my Pi (running 64 bit Raspberry OS)

`autostart-armcord-riitag-rpc.sh`:
```bash
#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}"

# Wait for internet access
while ! ping -q -c 1 "pool.ntp.org" > /dev/null 2>&1; do
  clear
  echo "Waiting for internet connection..."
done

# Start ArmCord
clear
ARMCORD_LOG="/tmp/armcord.log"
nohup armcord >"${ARMCORD_LOG}" 2>&1 &

# Wait for ArmCord
while ! cat "${ARMCORD_LOG}" | grep -qF '[Window state manager] [object Object]'; do
  clear
  echo "Waiting for ArmCord to finish loading..."
done
sleep 30 # rough amount of time needed for the rest of ArmCord to load

# Start RiiTag-RPC
xterm -maximized -e "./riitag-rpc"
```

**Comment by TheAlienDrew** [comment]
By the way, I have my account set to auto login, and I've put the script to auto start inside of `/etc/rc.local`

**Comment by TheAlienDrew** [comment]
> got the discord client to run (slowly) using box64 steps for ppl googling: 0. be on pi 3 or 4 and install 64 bit pi os
> 
> 1. get pi-apps: https://github.com/botspot/pi-apps
> 2. install box64
> 3. download discord tgz: https://discord.com/api/download?platform=linux&format=tar.gz
> 4. extract the tgz (to `/usr/local/bin/Discord`):
> 
> ```shell
> cd ~/Downloads
> sudo tar -xzvf -C /usr/local/bin/Discord
> ```
> 
> 5. (optional) copy the `Discord.desktop` file to the Desktop (you'll need to edit the `Exec` property:
> 
> ```shell
> cp /usr/local/bin/Discord/Discord.desktop ~/Desktop/Discord.desktop
> ```
> 
> 6. run discord:
> 
> ```shell
> box64 /usr/local/bin/Discord/Discord
> ```
> 
> 7. profit

When doing this, did you ever notice this bug happening? https://github.com/RiiConnect24/RiiTag-RPC/issues/29

**Comment by TheAlienDrew** [comment]
> ```shell
> sudo tar -xzvf -C /usr/local/bin/Discord
> ```

Also this line is wrong, you should probably fix it @libewa (missing the .tar.gz file in the parameters)

**Comment by TheAlienDrew** [comment]
Also it would probably be worth mentioning that the client needs to be started a few several times before it actually launches (at least while I was testing with booting the client directly from my Downloads folder).
