### ISSUE TITLE
RPI Binaries

### ISSUE THREAD

**Issue by TheAlienDrew** [RiiConnect24/RiiTag-RPC#32]
New ArmCord release: https://github.com/ArmCord/ArmCord/releases/tag/v3.2.1

Should fix the arRPC issues, and in turn, make RiiTag-RPC work.

I'll try testing later when I get home from work, but it should be prime time to include RPI Binaries with the releases.

**Comment by DismissedGuy** [comment]
Nice! I'll draft a new release right away, will ship once you can confirm it works.

**Comment by TheAlienDrew** [comment]
Checked it out, and it's all working properly now 🥳

**Comment by TheAlienDrew** [comment]
Though, if you download and test it yourself and think it's version 3.1.3, looks like that's just a weird minor bug, which I just reported here: https://github.com/ArmCord/ArmCord/issues/425

But it really is version 3.2.1, and works perfectly with RiiTag-RPC now.

**Comment by DismissedGuy** [comment]
Awesome. I've published the binaries in a new release: https://github.com/RiiConnect24/RiiTag-RPC/releases/tag/v1.3.2

I'll update the README with some short instructions.

**Comment by TheAlienDrew** [comment]
> Though, if you download and test it yourself and think it's version 3.1.3, looks like that's just a weird minor bug, which I just reported here: https://github.com/ArmCord/ArmCord/issues/425
> 
> But it really is version 3.2.1, and works perfectly with RiiTag-RPC now.

I guess this was just a bug affecting me because of how I originally installed ArmCord, so this can be ignored.
