### ISSUE TITLE
2 hours max for presence timeout?

### ISSUE THREAD

**Issue by chrisshanaz** [RiiConnect24/RiiTag-RPC#35]
any reason why the max presence timeout is 120 mins? A shame if I'm playing a game longer than 2 hours and then status just disappears

**Comment by KCRTR3** [comment]
there should be an option to change it

**Comment by DismissedGuy** [comment]
Those 120 minutes are indeed rather arbitrary; what would a better maximum be in your opinion?

**Comment by DismissedGuy** [comment]
Sounds reasonable, I'll see what I can do.

**Comment by DismissedGuy** [comment]
Hey! Sorry for taking so long, I just couldn't find the time. I bumped the max presence timeout from 120 to 720 (12 hours) in https://github.com/RiiConnect24/RiiTag-RPC/commit/c70e5ef5e16e7feec9b55648c139e394a77923fa. It will appear in the next release, which I will create in a bit.
