### ISSUE TITLE
incorrect game icon on my tag

### ISSUE THREAD

**Issue by benwywywywy** [RiiConnect24/RiiTag-RPC#36]
now im not sure if this is 3DS-RPC's fault or just RiiTag's fault but one of the games on my RiiTag shows up as a japanese dictionary game but it should be Tomodachi Collection New Life (Japanese Tomodachi Life)

**Comment by benwywywywy** [comment]
also i didn't know where to post this issue so i just posted it here

**Comment by DismissedGuy** [comment]
Hi! Just confirming that this is indeed the right place to post this 🙂 

Just to confirm, [this](https://www.gametdb.com/DS/CCUJ) is the game you were playing on your 3DS? Could you send a screenshot of the actual result? That should help to narrow down the problem.

**Comment by larsenv** [comment]
I think he meant this. https://www.gametdb.com/3DS/EC6J

By the way this has to do with RiiTag, not RiiTag-RPC.
