### ISSUE TITLE
Unable to start, missing dll "api-ms-win-core-path-l1-1-0.dll"

### ISSUE THREAD

**Issue by jonnyprogamer** [RiiConnect24/RiiTag-RPC#37]
Hi, i just finished setting up my RiiTag account and wanted to try this RPC for discord, but i can't start the program as im missing the library "api-ms-win-core-path-l1-1-0.dll", VC-Redist are fully up-to-date.
I downloaded the latest version and im on Windows 7 x64.

**Comment by DismissedGuy** [comment]
Hi,

Unfortunately pyinstaller, the tool we use to package the python source code, only supports Windows 8 and up. This means that we cannot provide official support Windows 7.

I'd recommend either upgrading your Windows version or installing Python manually and running the program from source.

If you're still running into this issue after trying the things above, feel free to reopen!

**Comment by jonnyprogamer** [comment]
Thanks, i already have python (altough a bit older version as the newest one does not run under 7) and will try to run it from source, thanks!

**Comment by jonnyprogamer** [comment]
> Hi,
> 
> Unfortunately pyinstaller, the tool we use to package the python source code, only supports Windows 8 and up. This means that we cannot provide official support Windows 7.
> 
> I'd recommend either upgrading your Windows version or installing Python manually and running the program from source.
> 
> If you're still running into this issue after trying the things above, feel free to reopen!

I installed all the requirements, ran the program and it's working perfectly (Python 3.8.10), maybe you can push an update with a fix for win 7 users (by changing the packaging tool) or write a warning on the readme.md that the built version doesn't work on windows 7?

**Comment by DismissedGuy** [comment]
I'm happy to hear that it works now!

Whether to support Windows 7 or not is up to the developers of pyinstaller, but I do agree that system support should be more clear. I'll see if I can clear that up in the README in the next few days.

**Comment by larsenv** [comment]
Unfortunately even though Windows 7 is very good it's becoming harder to be supported. You might want to upgrade some day. Just a suggestion.
