### ISSUE TITLE
Mark artifacts as executable

### ISSUE THREAD

**Issue by MeshariHat** [RiiConnect24/RiiTag-RPC#38]
How do i run the file on Mac? it just gave me a Data file. And the README is not clear

**Comment by larsenv** [comment]
Open Terminal then type in "chmod a+x <drag and drop the file to the file>". Then you can double click it to run it. @DismissedGuy why isn't the unix binaries chmodded?

**Comment by DismissedGuy** [comment]
> Open Terminal then type in "chmod a+x <drag and drop the file to the file>". Then you can double click it to run it. @DismissedGuy why isn't the unix binaries chmodded?

There's no special treatment for unix systems, and pyinstaller doesn't do it by default, so that's why. Should be an easy fix though, I can look into it later this week.

**Comment by DismissedGuy** [comment]
Fixed in the build pipeline, I will update the latest release binaries so they are executable.
