### ISSUE TITLE
The RiiTag Website doesn't work.

### ISSUE THREAD

**Issue by Simo3ds** [RiiConnect24/RiiTag-RPC#41]
I am in the RiiTag Website (tag.rc24.xyz)  but i have "Internal Server Error" and the website doesn't want to load the page.

**Comment by DismissedGuy** [comment]
Hi!

This is unfortunately not the right place to report your issue; this repository is purely for the RiiTag-RPC tool, not for the website itself. You're better off asking in the RiiConnect24 Discord or asking @larsenv .

**Comment by Simo3ds** [comment]
Thank you, i am gonna ask in the RiiConnect24 Discord Server

**Comment by SunsetSamu** [comment]
> The issue's fixed.

isn't yet, i'm trying to connect with a vpn from USA, Singapore, Netherlands, UK, and none of them works

**Comment by hwalker56** [comment]
> > The issue's fixed.
> 
> isn't yet, i'm trying to connect with a vpn from USA, Singapore, Netherlands, UK, and none of them works

@SunsetSamu this issue is over a year old. Rii/LinkTag is down rn as the server code needs to be rewritten, as the previous code caused conflicts with other services running on the same server. Until the rewrite is complete, the service will remain down.
