### ISSUE TITLE
Asset names not stable

### ISSUE THREAD

**Issue by theofficialgman** [RiiConnect24/RiiTag-RPC#43]
please keep asset names and types stable between releases and follow a pattern. it makes parsing through external tooling much easier.

you keep changing the naming style and what type of files are uploaded. the current release has zips with binaries contained. the previous release has binaries. the release before that again has zips

**Comment by malmeloo** [comment]
To my knowledge the format has changed exactly once, in the second to last release. I generally just upload whatever CI spits out, not entirely sure why I decided to change it there.

Anyway, the releases here aren't meant to be compatible with third-party tooling. They're meant to be read by humans. I'll try to keep it stable from now on, but I'm not gonna go out of my way to prevent potentially breaking changes for non-official download repositories. This repository is the only officially supported place to download RiiTag-RPC; I'm fine with you (or anyone else) including it in third-party repositories, but you can't expect me to maintain it there.

You might want to consider version pinning and having a maintainer keep it up-to-date. That would prevent these issues from arising.

**Comment by theofficialgman** [comment]
> You might want to consider version pinning and having a maintainer keep it up-to-date. That would prevent these issues from arising.

Version pinning is used already. Our CI automation that checks for new versions, automatically updates the pinned version, and then tests installation caught the change.

**Comment by malmeloo** [comment]
Ah, I thought it was some kind of latest-only download script. Still, I'd argue those fixes are part of the package maintenance experience, especially when you're unofficially packaging other projects.
