### ISSUE TITLE
dosent show my discord rpc

### ISSUE THREAD

**Issue by juiceboxx123** [RiiConnect24/RiiTag-RPC#45]
dosent show anything on discord

**Comment by Hassunaama** [comment]
Do you have Discord RPC turned off in your Discord settings (Settings => Activity Privacy => Share your detetected activities with others)?

**Comment by juiceboxx123** [comment]
i have it on but it dosent work

**Comment by malmeloo** [comment]
- How long ago did you boot up the game before checking Discord?
- Is your tag updated on the website when you launch a game?
- Is the game shown in the program after you launch it?
- Is activity sharing disabled in the privacy settings of the server you are checking it in?
- Are you running the program on the same PC as Discord?
- When you boot up the program, does it get stuck on "connecting to Discord"?
- Are there any other programs on your PC using Discord Rich Presence?

If all of that doesn't work, please send me a link to your RiiTag profile.

**Comment by malmeloo** [comment]
No response, feel free to reopen if you're still facing issues.
