### ISSUE TITLE
riitag website only works if i turn on a VPN

### ISSUE THREAD

**Issue by kassiesplatoon** [RiiConnect24/RiiTag-RPC#48]
whenever i try to go on the riitag website it won’t let me use it unless i turn on a VPN, i’m guessing it’s because i’m in russia, a lot of websites block my IP because of that

was this on purpose or can this please be fixed? waiting for my riitag to get edited with a vpn takes an eternity because the internet is so slow..

**Comment by malmeloo** [comment]
This is unrelated to RiiTag-RPC, so I am unable to help you with this, sorry. Try asking your question on Discord instead, I think you'll have better luck there.
